### ISSUE TITLE
Излишнее использование layout

### ISSUE THREAD

**Issue by ShkiTTer** [kralonur/NotForgot#1]
https://github.com/kralonur/NotForgot/blob/9553ba6b8604d49327c392d8e4ab861fa5c78260/app/src/main/res/layout/fragment_splash.xml#L2

layout нужен для DataBinding'а. В данном файле DataBinding отсутствует, а значит layout здесь не нужен. Он только порождает лишний сгенерированный код.

Похожая проблема есть во многих файлах. Их стоит поправить

**Comment by ShkiTTer** [comment]
https://github.com/kralonur/NotForgot/blob/9553ba6b8604d49327c392d8e4ab861fa5c78260/app/src/main/res/layout/fragment_register.xml#L2

Аналогично https://github.com/kralonur/NotForgot/issues/1#issuecomment-702753620

**Comment by ShkiTTer** [comment]
https://github.com/kralonur/NotForgot/blob/9553ba6b8604d49327c392d8e4ab861fa5c78260/app/src/main/res/layout/fragment_login.xml#L2

Аналогично https://github.com/kralonur/NotForgot/issues/1#issuecomment-702753620

**Comment by ShkiTTer** [comment]
https://github.com/kralonur/NotForgot/blob/9553ba6b8604d49327c392d8e4ab861fa5c78260/app/src/main/res/layout/layout_create.xml#L2

Аналогично https://github.com/kralonur/NotForgot/issues/1#issue-713639584

**Comment by kralonur** [comment]
Issue fixed by using viewbinding

**Comment by ShkiTTer** [comment]
Использование viewbinding с Kotlin практически бесполезно из-за наличие в Koltin синтетиков для доступа ко View

**Comment by kralonur** [comment]
> Использование viewbinding с Kotlin практически бесполезно из-за наличие в Koltin синтетиков для доступа ко View

KAE is not recommended by google. So it's better to apply guidelines, I guess. 
(Source: [source1](https://www.reddit.com/r/androiddev/comments/ala9p2/why_kotlinx_synthetic_is_no_longer_a_recommended),
[source2](https://www.reddit.com/r/androiddev/comments/ala9p2/why_kotlinx_synthetic_is_no_longer_a_recommended),
[image](https://miro.medium.com/max/1050/1*APXv8swJYGv2O8CAqV1jLQ.png)
