### ISSUE TITLE
Типы следует выносить в enum 

### ISSUE THREAD

**Issue by ShkiTTer** [kralonur/NotForgot#12]
https://github.com/kralonur/NotForgot/blob/e8d35e67573b0a14088888e013aa08016a279d15/app/src/main/java/com/example/notforgot/repository/ItemsRepository.kt#L97

https://github.com/kralonur/NotForgot/blob/e8d35e67573b0a14088888e013aa08016a279d15/app/src/main/java/com/example/notforgot/repository/ItemsRepository.kt#L107-L109

https://github.com/kralonur/NotForgot/blob/e8d35e67573b0a14088888e013aa08016a279d15/app/src/main/java/com/example/notforgot/repository/ItemsRepository.kt#L182

https://github.com/kralonur/NotForgot/blob/e8d35e67573b0a14088888e013aa08016a279d15/app/src/main/java/com/example/notforgot/repository/ItemsRepository.kt#L195-L201

Для таких вещей нужно заводить enum класс, а не пользоваться обычными строками

**Comment by kralonur** [comment]
Issue fixed.
