### ISSUE TITLE
Использование Converter для модели

### ISSUE THREAD

**Issue by ShkiTTer** [kralonur/NotForgot#13]
https://github.com/kralonur/NotForgot/blob/e8d35e67573b0a14088888e013aa08016a279d15/app/src/main/java/com/example/notforgot/repository/ItemsRepository.kt#L150-L167

https://github.com/kralonur/NotForgot/blob/e8d35e67573b0a14088888e013aa08016a279d15/app/src/main/java/com/example/notforgot/repository/ItemsRepository.kt#L128-L146

https://github.com/kralonur/NotForgot/blob/e8d35e67573b0a14088888e013aa08016a279d15/app/src/main/java/com/example/notforgot/repository/ItemsRepository.kt#L25-L34

Чтобы избежать частого повторения такого кода, следует написать Converter для моделей данных

**Comment by kralonur** [comment]
Issue fixed.
