### ISSUE TITLE
Навигация во ViewModel

### ISSUE THREAD

**Issue by ShkiTTer** [kralonur/NotForgot#14]
https://github.com/kralonur/NotForgot/blob/e8d35e67573b0a14088888e013aa08016a279d15/app/src/main/java/com/example/notforgot/ui/task_detail/TaskDetailViewModel.kt#L21-L27

Все перемещения между Activity/Fragment должны быть в классах Activity/Fragment. ViewModel в этом участия не принимает. Также излишне использовать для этого LiveData, когда можно было сразу открыть нужный экран

**Comment by kralonur** [comment]
Issue fixed.
