### ISSUE TITLE
Ненужное использование AndroidViewModel

### ISSUE THREAD

**Issue by ShkiTTer** [kralonur/NotForgot#15]
https://github.com/kralonur/NotForgot/blob/e8d35e67573b0a14088888e013aa08016a279d15/app/src/main/java/com/example/notforgot/ui/main/MainViewModel.kt#L12

Если во ViewModel нет необходимости использовать context или application, то стоит наследоваться от ViewModel, а не AndroidViewModel

**Comment by kralonur** [comment]
> https://github.com/kralonur/NotForgot/blob/e8d35e67573b0a14088888e013aa08016a279d15/app/src/main/java/com/example/notforgot/ui/main/MainViewModel.kt#L12
> 
> Если во ViewModel нет необходимости использовать context или application, то стоит наследоваться от ViewModel, а не AndroidViewModel

I used context for repository
https://github.com/kralonur/NotForgot/blob/e8d35e67573b0a14088888e013aa08016a279d15/app/src/main/java/com/example/notforgot/ui/main/MainViewModel.kt#L18-L19
