### ISSUE TITLE
Лишняя вложенность

### ISSUE THREAD

**Issue by ShkiTTer** [kralonur/NotForgot#3]
https://github.com/kralonur/NotForgot/blob/9553ba6b8604d49327c392d8e4ab861fa5c78260/app/src/main/res/layout/fragment_login.xml#L10

Так как в качестве корневого layout используется ConstraintLayout, то всю верстку можно и следует сделать используя его возможности. Вложенность ведет к проблемам с производительностью.

**Comment by ShkiTTer** [comment]
https://github.com/kralonur/NotForgot/blob/9553ba6b8604d49327c392d8e4ab861fa5c78260/app/src/main/res/layout/item_task_header.xml#L13

Здесь достаточно будет одного TextView внутри layout

**Comment by kralonur** [comment]
Issue fixed. With commit: https://github.com/kralonur/NotForgot/commit/26041c5217a14f2cb2a52ad01a1e8303ec53de3d
