### ISSUE TITLE
Установка слушателя клика в разметке

### ISSUE THREAD

**Issue by ShkiTTer** [kralonur/NotForgot#4]
https://github.com/kralonur/NotForgot/blob/9553ba6b8604d49327c392d8e4ab861fa5c78260/app/src/main/res/layout/item_task.xml#L20

Установка кликов в разметке является плохим тоном. Следует это делать из кода, в данном случае в классе ViewHolder

**Comment by ShkiTTer** [comment]
https://github.com/kralonur/NotForgot/blob/9553ba6b8604d49327c392d8e4ab861fa5c78260/app/src/main/res/layout/item_task.xml#L20

Аналогично https://github.com/kralonur/NotForgot/issues/4#issue-713645408

**Comment by kralonur** [comment]
Issue fixed.
