### ISSUE TITLE
Использование числовых значений в разметке

### ISSUE THREAD

**Issue by ShkiTTer** [kralonur/NotForgot#5]
https://github.com/kralonur/NotForgot/blob/9553ba6b8604d49327c392d8e4ab861fa5c78260/app/src/main/res/layout/fragment_login.xml#L13

Также как строки и цвета следует выносить в файл ресурсов. В данном случае dimens.xml. Стоит вынести часто используемые значения, например: 8dp, 16dp и так далее

**Comment by kralonur** [comment]
Issue fixed.
