### ISSUE TITLE
Неверное именование файлов

### ISSUE THREAD

**Issue by ShkiTTer** [kralonur/NotForgot#6]
https://github.com/kralonur/NotForgot/blob/master/app/src/main/res/layout/layout_detail_create.xml

Файл следовало назвать fragment_details. Это отражает его предназначение

**Comment by ShkiTTer** [comment]
https://github.com/kralonur/NotForgot/blob/master/app/src/main/res/layout/layout_lottie.xml

Файл используется для диалога загрузки. Поэтому следует назвать dialog_loading

**Comment by kralonur** [comment]
Issue fixed.
