### ISSUE TITLE
Использование group

### ISSUE THREAD

**Issue by ShkiTTer** [kralonur/NotForgot#7]
https://github.com/kralonur/NotForgot/blob/9553ba6b8604d49327c392d8e4ab861fa5c78260/app/src/main/res/layout/layout_detail_create.xml#L68-L73

Нет смысла оборачивать include в group, потому что include считается за один элемент. Если надо скрыть элементы, которые он содержит (как это делается в этом проекте), достаточно скрыть его

**Comment by ShkiTTer** [comment]
https://github.com/kralonur/NotForgot/blob/9553ba6b8604d49327c392d8e4ab861fa5c78260/app/src/main/res/layout/layout_detail_create.xml#L75-L80

Аналогично https://github.com/kralonur/NotForgot/issues/7#issue-713662430

**Comment by kralonur** [comment]
Issue fixed.
