### ISSUE TITLE
Одинаковые фрагменты с излишней логикой

### ISSUE THREAD

**Issue by ShkiTTer** [kralonur/NotForgot#9]
https://github.com/kralonur/NotForgot/blob/e8d35e67573b0a14088888e013aa08016a279d15/app/src/main/java/com/example/notforgot/ui/task_create/TaskCreateFragment.kt#L136-L138

https://github.com/kralonur/NotForgot/blob/e8d35e67573b0a14088888e013aa08016a279d15/app/src/main/java/com/example/notforgot/ui/task_detail/TaskDetailFragment.kt#L61-L63

Сейчас есть два одинаковых фрагмента, в которых есть include двух layout. Это плохо. Следует просто разнести эти вещи на два разных фрагмента и убрать не нужные include

**Comment by kralonur** [comment]
Issue fixed.
